eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ##注册中心显示IP
    hostname: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

server:
  port: 8764

##开启熔断器
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: feign
  datasource:
    url: jdbc:mysql://localhost:3306/boottest?useUnicode=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

  jpa:
    open-in-view: false
    database: MYSQL
    show-sql: true
    hibernate:
      namingStrategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    #password: root
    database: 2