package com.feign.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table permission
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Permission {
    /**
     * Database Column Remarks:
     *   权限编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_id
     *
     * @mbg.generated
     */
    private String permissionId;

    /**
     * Database Column Remarks:
     *   授权url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_url
     *
     * @mbg.generated
     */
    private String permissionUrl;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_comment
     *
     * @mbg.generated
     */
    private String permissionComment;

    /**
     * Database Column Remarks:
     *   权限状态,0正常，-1删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_status
     *
     * @mbg.generated
     */
    private String permissionStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_id
     *
     * @return the value of permission.permission_id
     *
     * @mbg.generated
     */
    public String getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_id
     *
     * @param permissionId the value for permission.permission_id
     *
     * @mbg.generated
     */
    public void setPermissionId(String permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_url
     *
     * @return the value of permission.permission_url
     *
     * @mbg.generated
     */
    public String getPermissionUrl() {
        return permissionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_url
     *
     * @param permissionUrl the value for permission.permission_url
     *
     * @mbg.generated
     */
    public void setPermissionUrl(String permissionUrl) {
        this.permissionUrl = permissionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_comment
     *
     * @return the value of permission.permission_comment
     *
     * @mbg.generated
     */
    public String getPermissionComment() {
        return permissionComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_comment
     *
     * @param permissionComment the value for permission.permission_comment
     *
     * @mbg.generated
     */
    public void setPermissionComment(String permissionComment) {
        this.permissionComment = permissionComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_status
     *
     * @return the value of permission.permission_status
     *
     * @mbg.generated
     */
    public String getPermissionStatus() {
        return permissionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_status
     *
     * @param permissionStatus the value for permission.permission_status
     *
     * @mbg.generated
     */
    public void setPermissionStatus(String permissionStatus) {
        this.permissionStatus = permissionStatus;
    }
}