package com.feign.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table role_permission
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class RolePermission {
    /**
     * Database Column Remarks:
     *   角色权限编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.role_permission_id
     *
     * @mbg.generated
     */
    private String rolePermissionId;

    /**
     * Database Column Remarks:
     *   角色编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.role_id
     *
     * @mbg.generated
     */
    private String roleId;

    /**
     * Database Column Remarks:
     *   权限编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.permission_id
     *
     * @mbg.generated
     */
    private String permissionId;

    /**
     * Database Column Remarks:
     *   角色权限状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.role_permission_status
     *
     * @mbg.generated
     */
    private String rolePermissionStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.role_permission_id
     *
     * @return the value of role_permission.role_permission_id
     *
     * @mbg.generated
     */
    public String getRolePermissionId() {
        return rolePermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.role_permission_id
     *
     * @param rolePermissionId the value for role_permission.role_permission_id
     *
     * @mbg.generated
     */
    public void setRolePermissionId(String rolePermissionId) {
        this.rolePermissionId = rolePermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.role_id
     *
     * @return the value of role_permission.role_id
     *
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.role_id
     *
     * @param roleId the value for role_permission.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.permission_id
     *
     * @return the value of role_permission.permission_id
     *
     * @mbg.generated
     */
    public String getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.permission_id
     *
     * @param permissionId the value for role_permission.permission_id
     *
     * @mbg.generated
     */
    public void setPermissionId(String permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.role_permission_status
     *
     * @return the value of role_permission.role_permission_status
     *
     * @mbg.generated
     */
    public String getRolePermissionStatus() {
        return rolePermissionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.role_permission_status
     *
     * @param rolePermissionStatus the value for role_permission.role_permission_status
     *
     * @mbg.generated
     */
    public void setRolePermissionStatus(String rolePermissionStatus) {
        this.rolePermissionStatus = rolePermissionStatus;
    }
}