server:
  port: 8763

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway
  ##是否与服务发现组件（register）进行结合 通过 serviceId（必须设置成大写）转发到具体的服务实例
  #http://Gateway_HOST:Gateway_PORT/ 大写的 serviceId/**
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      #path路由配置
#      routes:
#        ##限流
#      - id: requestratelimiter_route
#        uri: lb://eureka-server
#        predicates:
#        - After=2020-02-20T17:42:47.789+08:00
#        filters:
#        - name: RequestRateLimiter
#          args:
#            key-resolver: "#{@userKeyResolver}"
#            #用户每秒允许多少个请求
#            redis-rate-limiter.replenishRate: 1
#            #允许用户在一秒钟内执行的最大请求数
#            redis-rate-limiter.burstCapacity: 2
#            #请求花费多少令牌
#            #redis-rate-limiter.requestedTokens: 1