server:
  port: 8763

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8700/eureka/


spring:
  application:
    name: gateway
  ##是否与服务发现组件（register）进行结合 通过 serviceId（必须设置成大写）转发到具体的服务实例
  #http://Gateway_HOST:Gateway_PORT/ 大写的 serviceId/**
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      #path路由配置
      routes:
      #     - id: path_route
      #       uri: http://eureka-server
      #       predicates:
      #       - Path=/api/{segment}
      # 断言路由
      - id: after_route
        uri: lb://eureka-server
        predicates:
        - After=2020-02-20T17:42:47.789+08:00

  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
    database: 9