
eureka:
  client:
    serviceUrl:
    ##注册中心地址
      defaultZone: http://localhost:8761/eureka/
    #客户端拉取服务端注册列表的间隔
    registry-fetch-interval-seconds: 30
  server:
    ##节点超时时间 毫秒
    peer-node-read-timeout-ms: 3000
    #是否开启自动我保护 默认 true 节点失效自动删除 负载均衡使用
    enable-self-preservation: false
  instance:
    #是否以 IP 注册到注册中心
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #客户端发送给注册中心的心跳间隔时间
    lease-renewal-interval-in-seconds: 30
    #超过90秒还没有给注册中心发送第二次心跳则剔除下线
    lease-expiration-duration-in-seconds: 90

##RocketMq
rocketmq:
  nameServer: 192.168.1.18:9876
  producer:
    group: eurekaServer-group

server:
  port: 8762
spring:
  application:
    name: eurekaclient
  datasource:
    url: jdbc:mysql://localhost:3306/boottest?useUnicode=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

#adminServer的配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS