server:
  port: 8766

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




spring:
  application:
    name: demoAdmin
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      client:
        url: "http://localhost:8766"
management:
  endpoint:
    web:
      exposure:
        include: "*"


  #redis配置
  redis:
    #host: 127.0.0.1
    host: 192.168.1.9
    port: 6379
    #password: root
    password: magfin2018
    database: 9