server:
  port: 8766

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
eureka:
  client:
    serviceUrl:
      #http://localhost:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      user:




spring:
  application:
    name: demoAdmin
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      client:
        url: "http://localhost:8766"
      monitor:
        read-timeout: 20000s

#adminServer的配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    #password: root
    database: 9